## YAML Template.
---
server:
    port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: apigateway  
  cloud:
    gateway:
      routes:
      - id: customer_service
        uri: http://localhost:8081
        predicates:
        - Path=/**
    config:
      enabled: false