## YAML Template.
---
server:
  # Port where the application will run
  port: 8080

eureka:
  client:
    serviceUrl:
      # Eureka server URL, defaults to local if not set
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    # Setting the log level for Spring Cloud Gateway
    org.springframework.cloud.gateway: DEBUG
    # Setting the log level for Reactor Netty HTTP client
    reactor.netty.http.client: DEBUG

spring:
  application:
    # Application name for the Spring Boot application
    name: apigateway  

  cloud:
    gateway:
      # Defining the routes for the API Gateway
      routes:
      - id: customer_byCode
        # Load-balanced URI for the customer service
        uri: lb://businessdomain-customer
        # Predicate to match the URL path for this route
        predicates:
        - Path=/customer/v1/byCode/**
        filters:
          # Filter to apply for this route
          name: AuthenticationFiltering
      
      - id: customer_service
        # Load-balanced URI for the customer service
        uri: lb://businessdomain-customer
        # Predicate to match all paths for this route
        predicates:
        - Path=/customer/**
      
      - id: transaction_service
        # Load-balanced URI for the transaction service
        uri: lb/businessdomain-transactions
        # Predicates to match the URL path and HTTP methods for this route
        predicates:
          # Matches paths starting with /transaction/
        - Path=/transaction/**
          # Matches GET, POST, PUT, and DELETE HTTP methods
        - Method=GET,POST,PUT,DELETE
        # Filters to apply for this route
        filters:
          # Filter applied for authentication processing
        - name: AuthenticationFiltering


  # Disabling Spring Cloud configuration
  config:
    enabled: false