## YAML Template.
---
sprindoc:
    swagger-ui:
        path:
            swagger.html
        enabled: false
        
server:
  port: 48152
  
custom:
  activeprofileName: production
  
spring:
  jpa:
    show-sql: true
    datasource:
      url: jdbc:h2:mem:customer
      useraname: sa
      password: qwerty
      driver-class-name: org.h2.Driver
      
h2:
  console:
    enabled: true
    